main: pk.ajneb97.PlayerKits
version: ${project.version}
name: PlayerKits
api-version: 1.13
softdepend: [Vault, PlaceholderAPI]
author: Ajneb97
folia-supported: true

commands:
  kit:
    description: Main command of PlayerKits
    aliases: kits